-- native stuff
require("mysetup.remap")
require("mysetup.plugins")
require("mysetup.options")

-- libs
require("mysetup.mason")
require("mysetup.completion")
require("mysetup.lsp")
require("mysetup.formatting")
require("mysetup.treesitter")
require("mysetup.oil")
require("mysetup.fzf")
require("mysetup.gitsigns")
require("mysetup.harpoon")
require("mysetup.lualine")
require("mysetup.autopairs")
require("mysetup.autotag")
require("mysetup.gruvbox")
require("mysetup.dap")
require("nvim-web-devicons").setup()
